### ISSUE TITLE
ZIP64 issue when command line backup

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#171]
This command 
```python manage.py backup create /home/ideaserverKoomBook.zip --no-input```
issue this 
```Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.virtualenvs/ideasbox/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/root/.virtualenvs/ideasbox/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.virtualenvs/ideasbox/local/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.virtualenvs/ideasbox/local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/ideasbox.lan/ideasbox/serveradmin/management/commands/backup.py", line 37, in handle
    backup = Backup.create()
  File "/home/ideasbox.lan/ideasbox/serveradmin/backup.py", line 80, in create
    backup.save()
  File "/home/ideasbox.lan/ideasbox/serveradmin/backup.py", line 62, in save
    base_dir='./'
  File "/usr/lib/python2.7/shutil.py", line 548, in make_archive
    filename = func(base_name, base_dir, **kwargs)
  File "/usr/lib/python2.7/shutil.py", line 458, in _make_zipfile
    logger.info("adding '%s'", path)
  File "/usr/lib/python2.7/zipfile.py", line 801, in __exit__
    self.close()
  File "/usr/lib/python2.7/zipfile.py", line 1345, in close
    " would require ZIP64 extensions")
zipfile.LargeZipFile: Central directory offset would require ZIP64 extensions```

Is it related to a python module ?

**Comment by yohanboniface** [comment]
Can you have a try with latest master?

**Comment by yohanboniface** [comment]
Humm, just a check: are you on 64-bits system?

**Comment by fheslouin** [comment]
Nop i'm on ARM system, I'll have a try with the latest master

**Comment by yohanboniface** [comment]
> Nop

That may be the issue :/

**Comment by yohanboniface** [comment]
cc @barbayellow someone in the sprint may have a clear idea of what's going here, and maybe a fix/workaround; we seem to hit some 32 bits limits.

**Comment by barbayellow** [comment]
Sorry, Missed that today. I'll make sure to ask the question tomorrow.

**Comment by yohanboniface** [comment]
@fheslouin you can now set the format to be used with setting `BACKUP_FORMAT = 'xxx'`, choosing one of `zip`, `tar`, `bztar`, `gztar`, see https://docs.python.org/2/library/tarfile.html for a bit more doc about tar formats.

**Comment by fheslouin** [comment]
I tried again : 

From the command line
```
export BACKUP_FORMAT='gztar'
```
then
```
sudo ideascube backup create /media/hdd/ideascube.tgz --no-input
IDEASCUBE_ID=koombook281
Importing settings from ideascube.conf.dev
```
The script ran for about 20min and end up like this : 
```
Traceback (most recent call last):
  File "/usr/share/python/ideascube/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/ideascube/serveradmin/management/commands/backup.py", line 37, in handle
    backup = Backup.create()
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/ideascube/serveradmin/backup.py", line 115, in create
    backup.save()
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/ideascube/serveradmin/backup.py", line 79, in save
    base_dir='./'
  File "/usr/lib/python2.7/shutil.py", line 548, in make_archive
    filename = func(base_name, base_dir, **kwargs)
  File "/usr/lib/python2.7/shutil.py", line 458, in _make_zipfile
    logger.info("adding '%s'", path)
  File "/usr/lib/python2.7/zipfile.py", line 801, in __exit__
    self.close()
  File "/usr/lib/python2.7/zipfile.py", line 1345, in close
    " would require ZIP64 extensions")
zipfile.LargeZipFile: Central directory offset would require ZIP64 extensions
```
I'm not sure at 100% the script takes correctly the ```export BACKUP_FORMAT='gztar'``` but I guess it should !

**Comment by fheslouin** [comment]
By the way, I looked in STORAGE_ROOT
```
STORAGE_ROOT = '/media/hdd/ideascube/storage'
```
I found a zip file of 2.1 Go
```
/media/hdd/ideascube/storage/backups/BsfCampus-0.4.0-201510271247.zip
```
I Don't know why the backup ended here

**Comment by yohanboniface** [comment]
> I Don't know why the backup ended up here

That's the expected place: STORAGE_ROOT + 'backups'

BACKUP_FORMAT should be set in your python settings, so in your bsfCampus.py module :)

**Comment by fheslouin** [comment]
Ok, so I no need to give a path in the backup command  ?
```ideascube backup create /media/hdd/ideascube.tgz --no-input```

I put BACKUP_FORMAT in my bsfCampus.py conf file and try again 

Thank

**Comment by yohanboniface** [comment]
I'll also add a --format option to the management command, btw.

**Comment by yohanboniface** [comment]
> Ok, so I no need to give a path in the backup command ?

Nope, try:

    sudo -u ideascube ideascube backup create
