### ISSUE TITLE
UnicodeDecodeError on import_medias

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#203]
An other UnicodeDecodeError
```
⚠ Skipping. Document exists. Use --update to reimport data.
- lang: fr
- kind: pdf
- tags: Atelier VDC, Scratch
- title: Activité “le tri sélectif”
- summary: Fiche Activité Scratch. But du jeu : Nous allons créer une activité de type  glisser-déposer ". Différents déchets apparaissent en haut de l’écran. Avec la souris, il faut les faire glisser dans la bonne poubelle. Il est possible d’ajouter un compteur de points et un chronomètre afin de rendre le jeu plus ludique. Pour programmer ce jeu, nous allons utiliser la plateforme Scratch qui a l’avantage d’utiliser du code visuel : pas besoin d’apprendre un langage de programmation pour construire ses propres jeux vidéo !"
- credits: Voyageurs du Code
- path: Tri sélectif.pdf
--------------------
Traceback (most recent call last):
  File "/usr/share/python/ideascube/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/ideascube/mediacenter/management/commands/import_medias.py", line 59, in handle
    self.add(row)
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/ideascube/mediacenter/management/commands/import_medias.py", line 65, in add
    title = smart_truncate(title)
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/ideascube/templatetags/ideascube_tags.py", line 116, in smart_truncate
    s = u' '.join(s.split(u' ')[0:-1])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 38: ordinal not in range(128)
```
Here is the CSV line : 
```
But du jeu : Nous allons créer une activité de type " glisser-déposer ". Différents déchets apparaissent en haut de l’écran. Avec la souris, il faut les faire glisser dans la bonne poubelle. Il est possible d’ajouter un compteur de points et un chronomètre afin de rendre le jeu plus ludique. Pour programmer ce jeu, nous allons utiliser la plateforme Scratch qui a l’avantage d’utiliser du code visuel : pas besoin d’apprendre un langage de programmation pour construire ses propres jeux vidéo !";fr;Voyageurs du Code;Atelier VDC, Scratch;Tri sélectif.pdf
```

**Comment by yohanboniface** [comment]
Can you give me the line after this one instead, that's the one that triggers the bug? :)

**Comment by fheslouin** [comment]
You're right, I think this line is triggering the bug : 
```
pdf;Changement climatique, comprendre et réagir : Quelles sont les conséquences du réchauffement de la planète ?;"L’exposition pédagogique " Changements Climatiques : Comprendre et Réagir " (2011) présente de façon simple et colorée les principales informations sur les connaissances actuelles en matière de changements climatiques.  
Cette affiche illustre les impacts néfastes du changement climatique : les menaces sur les équilibres climatiques, écologiques et humains.";fr;Réseau Action Climat;changement climatique, climat;Affiches_Changementc_climatiques_comprendre_et_reagir_Partie3.pdf 
```
I think it's comming from the return line after ```climatiques.```

**Comment by yohanboniface** [comment]
If you try without the carriage return, it passes?

**Comment by fheslouin** [comment]
It was coming from from the ```“```. Most of the files are containing those king of bad characters :(

**Comment by yohanboniface** [comment]
OK, but that should not fail anyway. I suspect your file no to be in utf-8.
I've added a `--encoding` parameter, can you try with `--encoding latin1`?

**Comment by fheslouin** [comment]
My file was in utf-8, here is a new sample, now I suspect that some space are not well encoded.

```
⚠ Skipping. Document exists. Use --update to reimport data.
- lang: fr
- kind: pdf
- tags: Atelier VDC, enfants
- title: Parcours pégagogique enfants
- summary: Fiches à récupérer pour le parcours pédagogique enfants: Atelier Déconnecté Programmation Orale, Atelier Déconnecté Devine ton Chiffre, Fiche Scratch débutants (Ghostbuster par exemple),Cartes Scratchs, Permis Scratch
- credits: Voyageurs du Code
- path: Parcours_pédagogique_enfant.pdf
--------------------
Traceback (most recent call last):
  File "/usr/share/python/ideascube/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/ideascube/mediacenter/management/commands/import_medias.py", line 62, in handle
    self.add(row)
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/ideascube/mediacenter/management/commands/import_medias.py", line 68, in add
    title = smart_truncate(title)
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/ideascube/templatetags/ideascube_tags.py", line 116, in smart_truncate
    s = u' '.join(s.split(u' ')[0:-1])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 38: ordinal not in range(128)
```
and the csv
```
pdf;Parcours pégagogique enfants;Fiches à récupérer pour le parcours pédagogique enfants: Atelier Déconnecté Programmation Orale, Atelier Déconnecté Devine ton Chiffre, Fiche Scratch débutants (Ghostbuster par exemple),Cartes Scratchs, Permis Scratch;fr;Voyageurs du Code;Atelier VDC, enfants;Parcours_pédagogique_enfant.pdf
pdf;Changement climatique, comprendre et réagir: Les gaz à effet de serre Qui sont-ils ? D’où viennent-ils ?;L’exposition pédagogique Changements Climatiques : Comprendre et Réagir (2011) présente de façon simple et colorée les principales informations sur les connaissances actuelles en matière de changements climatiques. Cette affiche met en avant les rejets de gaz à effet de serre d’origine humaine, leurs principales causes et leur répartition au niveau mondial et français.;fr;Réseau Action Climat;changement climatique, climat, effet de serre;Affiches_Changementc_climatiques_comprendre_et_reagir_Partie2.pdf
pdf;Changement climatique, comprendre et réagir : Quelles sont les conséquences du réchauffement de la planète ?;L’exposition pédagogique  Changements Climatiques : Comprendre et Réagir  (2011) présente de façon simple et colorée les principales informations sur les connaissances actuelles en matière de changements climatiques. Cette affiche illustre les impacts néfastes du changement climatique : les menaces sur les équilibres climatiques, écologiques et humains.;fr;Réseau Action Climat;changement climatique, climat;Affiches_Changementc_climatiques_comprendre_et_reagir_Partie3.pdf
```

**Comment by yohanboniface** [comment]
Can you send me the whole file by email? :)

**Comment by fheslouin** [comment]
done !
