### ISSUE TITLE
MemoryError on impor_medias

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#206]
I got this error on importing a video of 248 Mo

```
Traceback (most recent call last):
  File "/usr/share/python/ideascube/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/ideascube/mediacenter/management/commands/import_medias.py", line 62, in handle
    self.add(row)
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/ideascube/mediacenter/management/commands/import_medias.py", line 94, in add
    content_type=content_type)
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/django/core/files/uploadedfile.py", line 114, in __init__
    super(SimpleUploadedFile, self).__init__(BytesIO(content), None, name,
MemoryError
```
Is there any upload restriction ?

**Comment by yohanboniface** [comment]
ouch, how much RAM do you have on the device?

**Comment by fheslouin** [comment]
I have got 1Go of RAM, by the time there was 349Mo left on the total. 
Do you think it is related directly to the RAM ?

If I recall I have been able to upload more than 250Mo with the web interface.

**Comment by bochecha** [comment]
This reads the whole file to upload in memory, all at once:

https://github.com/ideascube/ideascube/blob/master/ideascube/mediacenter/management/commands/import_medias.py#L93-L94

This is clearly going to cause memory issues with big files.

**Comment by yohanboniface** [comment]
> This is clearly going to cause memory issues with big files.

Yep, this need to be fixed :)

**Comment by fheslouin** [comment]
Ok, great that we found about this issue :)

**Comment by Natim** [comment]
We could handle the uploaded file with chuncks (http://stackoverflow.com/a/23139023/186202)

**Comment by yohanboniface** [comment]
Fixed through https://github.com/ideascube/ideascube/pull/228

**Comment by yohanboniface** [comment]
Still consuming too much RAM at import, reopening.

**Comment by yohanboniface** [comment]
humm, well, but I see no error, when the is no more RAM the python consuming seems flushed, and import continue without issue, so guess it's ok.
