### ISSUE TITLE
Media import crashes because of a single quote

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#258]
It seems the import using the "ideascube import_medias" command crashed because of a specific single quote. The import file with the single quote is attached. The first field with such a character is line 7, description field : "Les 'Kashashs' sont des colombophiles (éleveurs de pigeons voyageurs) à la réputation sulfureuse exerçant sur les terrasses de Damas. Ils sont réputés voleurs, menteurs, bagarreurs. L'un d'eux nous parle de sa passion."

I renamed it as a text file for the purpose of the upload in github.

[movies.txt](https://github.com/ideascube/ideascube/files/71774/movies.txt)

**Comment by yohanboniface** [comment]
Can you also paste the traceback if you still have it by hand?

**Comment by barbayellow** [comment]
Here is the traceback

----------------------

[20602:20601 0:209] 04:10:13 jeu. déc. 24 [ideascube@idb-bdi-bwagiriza-928:/dev/pts/4 +1] ~/medias_import 
(1:209)$ ideascube import_medias --update movies.csv 
IDEASCUBE_ID=idb_bdi_bwagiriza
Importing settings from ideascube.conf.idb_bdi_bwagiriza
{'lang': 'fr', '': '', 'kind': 'videos', 'title': 'Portrait de Sira Sissoko', 'summary': "Sira Sissoko est l'une des rares femmes artistes peintres du Mali. Son travail cr\xc3\xa9atif s\xe2\x80\x99appuie sur des supports artistiques compos\xc3\xa9s de papier recycl\xc3\xa9 et de fibres v\xc3\xa9g\xc3\xa9tales. Sira Sissoko dirige l\xe2\x80\x99atelier Papier Mali et est \xc3\xa9galement professeur d\xe2\x80\x99histoire de l\xe2\x80\x99art \xc3\xa0 l\xe2\x80\x99Institut National des Arts de Bamako. Tr\xc3\xa8s engag\xc3\xa9e, elle initie des femmes en difficult\xc3\xa9 au recyclage du papier usag\xc3\xa9 et elle est membre de l\xe2\x80\x99Association des femmes plasticiennes du Mali dont le but est de soutenir les femmes qui se lancent dans une carri\xc3\xa8re artistique.", 'credits': "Auteur/R\xc3\xa9alisateur : Afrik'art | Date : 2012 | Public : adolescents et adultes | Dur\xc3\xa9e : 4'28", 'tag': 'art', 'path': 'sirasissoko.webm'}
✔ Uploaded media Portrait de Sira Sissoko
{'lang': 'fr', '': None, 'kind': 'videos', 'title': 'Portrait de Kettly No\xc3\xabl', 'summary': 'Ha\xc3\xaftienne n\xc3\xa9e \xc3\xa0 Port-au-Prince, Kettly No\xc3\xabl est chor\xc3\xa9graphe. Elle s\xe2\x80\x99est install\xc3\xa9e au Mali en 2000, o\xc3\xb9 elle a cr\xc3\xa9\xc3\xa9 sa compagnie de danse contemporaine \xe2\x80\x98Donko S\xc3\xa9ko\xe2\x80\x99 qui tient chaque ann\xc3\xa9e, un festival de danse contemporaine.', 'credits': "Auteur/R\xc3\xa9alisateur : Afrik'art | Date : 2012 | Dur\xc3\xa9e : 5'18 | Public : adolescents et adultes", 'tag': 'art', 'path': 'kettlynoel.webm'}
Traceback (most recent call last):
  File "/usr/share/python/ideascube/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/ideascube/mediacenter/management/commands/import_medias.py", line 74, in handle
    for row in rows:
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/ideascube/mediacenter/management/commands/import_medias.py", line 22, in UnicodeDictReader
    for key, value in row.iteritems()}
  File "/usr/share/python/ideascube/local/lib/python2.7/site-packages/ideascube/mediacenter/management/commands/import_medias.py", line 22, in <dictcomp>
    for key, value in row.iteritems()}
AttributeError: 'NoneType' object has no attribute 'decode'
