### ISSUE TITLE
package manager: DownloadError not catched

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#306]
```
Traceback (most recent call last):
  File "/usr/share/python/ideascube/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/ideascube/serveradmin/management/commands/catalog.py", line 105, in handle
    options['func'](options)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/ideascube/serveradmin/management/commands/catalog.py", line 151, in install_packages
    self.catalog.install_packages(options['ids'])
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/ideascube/serveradmin/catalog.py", line 440, in install_packages
    download_path = self._fetch_package(pkg)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/ideascube/serveradmin/catalog.py", line 405, in _fetch_package
    reporthook=_progress)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/resumable/__init__.py", line 110, in urlretrieve
    raise DownloadError(check)
resumable.DownloadError: DownloadCheck.checksum_mismatch
```

**Comment by yohanboniface** [comment]
Fixed by #327
