### ISSUE TITLE
Package manager: missing permissions to create Nginx vhost

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#307]
```
Traceback (most recent call last):
  File "/usr/share/python/ideascube/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/ideascube/serveradmin/management/commands/catalog.py", line 105, in handle
    options['func'](options)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/ideascube/serveradmin/management/commands/catalog.py", line 151, in install_packages
    self.catalog.install_packages(options['ids'])
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/ideascube/serveradmin/catalog.py", line 449, in install_packages
    handler.commit()
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/ideascube/serveradmin/catalog.py", line 151, in commit
    self.register_site(pkg)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/ideascube/serveradmin/catalog.py", line 161, in register_site
    with available.open('w') as f:
  File "/usr/lib/python3.4/pathlib.py", line 1073, in open
    opener=self._opener)
  File "/usr/lib/python3.4/pathlib.py", line 947, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/lib/python3.4/pathlib.py", line 323, in wrapped
    return strfunc(str(pathobj), *args)
PermissionError: [Errno 13] Permission denied: '/etc/nginx/sites-available/w2eu'
```
I'm running with sudo for now. Not sure this will not have side effects. And when this will be run from GUI, we'll need a smarted solution anyway.

**Comment by yohanboniface** [comment]
Closing as superseded by #431
