### ISSUE TITLE
Error when trying to add local catalog.yml

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#470]
I tried to add a local catalog.yml 

```
root@debian:/usr/local/share/kiwix# ideascube catalog remotes add "kiwix" "Temporary catalog" catalog.yml 
IDEASCUBE_ID=
Importing settings from ideascube.conf.base

Traceback (most recent call last):
  File "/usr/share/python/ideascube/bin/django-admin", line 9, in <module>
    load_entry_point('Django==1.9.8', 'console_scripts', 'django-admin')()
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/ideascube/serveradmin/management/commands/catalog.py", line 116, in handle
    options['func'](options)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/ideascube/serveradmin/management/commands/catalog.py", line 229, in add_remote
    self.catalog.update_cache()
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/ideascube/serveradmin/catalog.py", line 772, in update_cache
    urlretrieve(remote.url, tmppath, reporthook=_progress)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/resumable/__init__.py", line 108, in urlretrieve
    headers=headers, **kwargs)) as resp:
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/requests/sessions.py", line 461, in request
    prep = self.prepare_request(req)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/requests/sessions.py", line 394, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/requests/models.py", line 294, in prepare
    self.prepare_url(url, params)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/requests/models.py", line 354, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'catalog.yml': No schema supplied. Perhaps you meant http://catalog.yml?

```

**Comment by bochecha** [comment]
Yes, you need to pass an actual URL. That would be `file:///the/absolute/path/to/your/file`.

Except... last I checked `resumable-urlretrieve` didn't handle `file://` URLs :disappointed: 

So there are two things here:

* we should provide a decent error message
* maybe we should add support for local catalog files?
