### ISSUE TITLE
Ideascube catalog install fail with wrong locale

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#480]
Ideascube catalog fail when installing package with wrong locale 

```
# Pastebin bfe4Ggtl
Rebuilding the Kiwix library
Traceback (most recent call last):
  File "/usr/share/python/ideascube/bin/django-admin", line 9, in <module>
    load_entry_point('Django==1.9.8', 'console_scripts', 'django-admin')()
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/ideascube/serveradmin/management/commands/catalog.py", line 116, in handle
    options['func'](options)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/ideascube/serveradmin/management/commands/catalog.py", line 175, in install_packages
    self.catalog.install_packages(options['ids'])
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/ideascube/serveradmin/catalog.py", line 626, in install_packages
    handler.commit()
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/ideascube/serveradmin/catalog.py", line 155, in commit
    et = etree.parse(f)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:79840)
  File "src/lxml/parser.pxi", line 1814, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:116442)
  File "src/lxml/parser.pxi", line 1834, in lxml.etree._parseFilelikeDocument (src/lxml/lxml.etree.c:116734)
  File "src/lxml/parser.pxi", line 1729, in lxml.etree._parseDocFromFilelike (src/lxml/lxml.etree.c:115495)
  File "src/lxml/parser.pxi", line 1150, in lxml.etree._BaseParser._parseDocFromFilelike (src/lxml/lxml.etree.c:110369)
  File "src/lxml/parser.pxi", line 584, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:103583)
  File "src/lxml/parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:105196)
  File "src/lxml/lxml.etree.pyx", line 324, in lxml.etree._ExceptionContext._raise_if_stored (src/lxml/lxml.etree.c:10740)
  File "src/lxml/parser.pxi", line 362, in lxml.etree._FileReaderContext.copyToBuffer (src/lxml/lxml.etree.c:100948)
  File "/usr/share/python/ideascube/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd9 in position 232: ordinal not in range(128)
```

**Comment by yohanboniface** [comment]
`locale` ? :)

**Comment by bochecha** [comment]
@yohanboniface Yes, @fheslouin's locale-over-ssh problem as usual.

However I asked him to open a ticket anyway, because I think we might still be doing something wrong here.

The [lxml documentation](http://lxml.de/tutorial.html#the-parse-function) says:

> The parse() function supports any of the following sources:
> * an open file object (make sure to open it in binary mode)

And [we're not](https://github.com/ideascube/ideascube/blob/master/ideascube/serveradmin/catalog.py#L155-L156)

So there might still be something we should do on the code side.
