### ISSUE TITLE
Missing configuration_configuration table after installing ideascube 0.17.0

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#654]
I can't really tell this is an ideascube issue, but I don't understand where this is coming from.

Ideascube is working correctly, as I can update the catalog, but installing a new package end to an error
```
ideascube@kb-bsf-scaleway-940:/root$ ideascube catalog cache update
IDEASCUBE_ID=kb
Importing settings from ideascube.conf.kb

Download: 100.00% |⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛| 16.0 KiB/2.6 KiB (0.0 KiB/s) | ETA: 17:34:33
Download: 100.00% |⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛| 48.0 KiB/34.7 KiB (0.0 KiB/s) | ETA: 17:34:33
Download: 100.00% |⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛| 16.0 KiB/1.8 KiB (0.0 KiB/s) | ETA: 17:34:35
```
Here is the error. This can be corrected by running `ideascube migrate`
```
ideascube@kb-bsf-scaleway-940:/root$ ideascube catalog install phet.en
IDEASCUBE_ID=kb
Importing settings from ideascube.conf.kb

phet.en is already installed
Traceback (most recent call last):
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: configuration_configuration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/share/python/ideascube/bin/django-admin", line 9, in <module>
    load_entry_point('Django==1.10.3', 'console_scripts', 'django-admin')()
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/ideascube/serveradmin/management/commands/catalog.py", line 116, in handle
    options['func'](options)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/ideascube/serveradmin/management/commands/catalog.py", line 175, in install_packages
    self.catalog.install_packages(options['ids'])
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/ideascube/serveradmin/catalog.py", line 680, in install_packages
    self._update_displayed_packages_on_home(to_add_ids=installed_ids)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/ideascube/serveradmin/catalog.py", line 640, in _update_displayed_packages_on_home
    displayed_packages = get_config('home-page', 'displayed-package-ids')
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/ideascube/configuration/__init__.py", line 41, in get_config
    config = Configuration.objects.get(namespace=namespace, key=key)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/db/models/query.py", line 379, in get
    num = len(clone)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/db/models/query.py", line 238, in __len__
    self._fetch_all()
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/share/python/ideascube/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: configuration_configuration
```

**Comment by bochecha** [comment]
That means `ideascube migrate` hadn't been run correctly.

Nothing will work if `migrate` hasn't been run correctly.

So, first question, did you run it at all? If yes, the problem becomes why didn't `migrate` do its job completely.

**Comment by fheslouin** [comment]
I did not run it manually. AnsibleCube has been doing the regular process of installing ideascube.
I guess `migrate` has not be done correctly. But logs does not show any error. 

This error only occur on crashbook (our ARM pre-prod), we might have something different on that device...

**Comment by bochecha** [comment]
Would be nice if you can reproduce it by manually installing the ideascube package.

**Comment by fheslouin** [comment]
Here is the error, when reproducing manually 
```
apt-get install uwsgi nginx
```
then 
```
apt-get install ideascube
```
The error occur at the end of the process : 
```
481 static files copied to '/var/ideascube/static', 481 post-processed.
Linking Nginx VHost
Linking uWSGI app
Setting permissions on the uWSGI log folder
Restarting Nginx and uWSGI
Job for nginx.service failed. See 'systemctl status nginx.service' and 'journalctl -xn' for details.
dpkg: error processing package ideascube (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up libglib2.0-data (2.42.1-1) ...
Setting up libmbim-proxy (1.10.0-2.1) ...
Setting up libqmi-proxy (1.10.2-2) ...
Setting up modemmanager (1.4.0-1) ...
Setting up ppp (2.4.6-3.1) ...
Setting up shared-mime-info (1.3-1) ...
Setting up xdg-user-dirs (0.15-2) ...
Setting up iputils-arping (3:20121221-5+b2) ...
Setcap worked! arping is not suid!
Setting up usb-modeswitch-data (20150115-1) ...
Setting up usb-modeswitch (2.2.0+repack0-2) ...
Processing triggers for libc-bin (2.19-18+deb8u3) ...
Processing triggers for dbus (1.8.20-0+deb8u1) ...
Processing triggers for systemd (215-17+deb8u5) ...
Errors were encountered while processing:
 ideascube
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Here is the result of nginx status : 
```
root@crashbook:~# systemctl status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled)
   Active: failed (Result: exit-code) since Wed 2016-12-14 17:03:26 UTC; 4min 11s ago
 Main PID: 5324 (code=exited, status=0/SUCCESS)

Dec 14 17:03:26 crashbook nginx[8851]: nginx: [emerg] a duplicate default server for 0.0.0.0:80 in /etc/nginx/sites-enabled/ideascube:9
Dec 14 17:03:26 crashbook nginx[8851]: nginx: configuration file /etc/nginx/nginx.conf test failed
Dec 14 17:03:26 crashbook systemd[1]: nginx.service: control process exited, code=exited status=1
Dec 14 17:03:26 crashbook systemd[1]: Failed to start A high performance web server and a reverse proxy server.
Dec 14 17:03:26 crashbook systemd[1]: Unit nginx.service entered failed state.
```
dpkg.log says 
```
2016-12-14 17:01:47 status half-configured ideascube:armhf 0.17.0
```

But this is not related to the above issue directly. I have been able to install manually `phet.en` package without doing any `ideascube migrate`

**Comment by bochecha** [comment]
> But this is not related to the above issue directly. I have been able to install manually phet.en package without doing any ideascube migrate

Like I said, that's not an issue.

It is **expected** that you can't install packages without first running `migrate`.

And `migrate` didn't get run at install time because of the nginx issue.

**Comment by fheslouin** [comment]
AnsibleCube was moving the ideascube folder at the wrong time. 
This has been solved in : https://github.com/ideascube/ansiblecube/commit/7608d2120551eb2b091688aaa7453aeac4262e9c
